# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.io import (
    set_patrols_and_patrol_events_params as set_patrols_and_patrol_events_params,
)
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_patrols_from_combined_params = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_patrols_from_combined_params",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.transformation import (
    convert_column_values_to_numeric as convert_column_values_to_numeric,
)
from ecoscope.platform.tasks.transformation import (
    convert_column_values_to_string as convert_column_values_to_string,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)

get_patrol_observations_from_patrols_df_and_combined_params = (
    create_func_magicmock(  # 🧪
        anchor="ecoscope.platform.tasks.io",  # 🧪
        func_name="get_patrol_observations_from_patrols_df_and_combined_params",  # 🧪
    )
)  # 🧪
from ecoscope.platform.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope.platform.tasks.io import (
    unpack_events_from_patrols_df_and_combined_params as unpack_events_from_patrols_df_and_combined_params,
)
from ecoscope.platform.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import create_path_layer as create_path_layer
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import with_unit as with_unit
from ecoscope_workflows_ext_custom.tasks.io import (
    get_spatial_features as get_spatial_features,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    load_local_spatial_file as load_local_spatial_file,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_spatial_features_layer as create_spatial_features_layer,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    apply_qualitative_color_map as apply_qualitative_color_map,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    collect_optional_layers as collect_optional_layers,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    extract_first_value_as_string as extract_first_value_as_string,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    extract_formatted_datetime as extract_formatted_datetime,
)

get_event_type_display_names_from_events = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_event_type_display_names_from_events",  # 🧪
)  # 🧪

get_events = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)

process_events_details = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.analysis import dataframe_count as dataframe_count
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_map as draw_map
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import (
    view_state_from_layers as view_state_from_layers,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_icmbio.tasks import add_lat_lon_to_gdf as add_lat_lon_to_gdf
from ecoscope_workflows_ext_icmbio.tasks import (
    format_individual_patrol_event_details as format_individual_patrol_event_details,
)

download_event_attachments = create_func_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="download_event_attachments",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_custom.tasks.io import (
    remove_file_scheme as remove_file_scheme,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    gather_icmbio_dashboard as gather_icmbio_dashboard,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    generate_individual_patrol_report as generate_individual_patrol_report,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    prepare_individual_patrol_report_context as prepare_individual_patrol_report_context,
)


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    base_maps = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_maps") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[], **(params.get("groupers") or {}))
        .call()
    )

    patrol_id = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("patrol_id")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("patrol_id") or {}))
        .call()
    )

    patrol_and_events_params = (
        task(set_patrols_and_patrol_events_params)
        .validate()
        .set_task_instance_id("patrol_and_events_params")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            patrol_types=[],
            event_types=[],
            status=["done", "active", "overdue", "cancelled"],
            event_states=[],
            sub_page_size=100,
            raise_on_empty=False,
            include_patrol_details=True,
            truncate_to_time_range=True,
            include_null_geometry=False,
            patrols_overlap_daterange=True,
            **(params.get("patrol_and_events_params") or {}),
        )
        .call()
    )

    all_patrols = (
        task(get_patrols_from_combined_params)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("all_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=patrol_and_events_params,
            **(params.get("all_patrols") or {}),
        )
        .call()
    )

    all_patrols_serial_as_str = (
        task(convert_column_values_to_string)
        .validate()
        .set_task_instance_id("all_patrols_serial_as_str")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=all_patrols,
            columns=["serial_number"],
            **(params.get("all_patrols_serial_as_str") or {}),
        )
        .call()
    )

    selected_patrol = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("selected_patrol")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=all_patrols_serial_as_str,
            column="serial_number",
            values=[patrol_id],
            **(params.get("selected_patrol") or {}),
        )
        .call()
    )

    selected_patrol_serial_as_int = (
        task(convert_column_values_to_numeric)
        .validate()
        .set_task_instance_id("selected_patrol_serial_as_int")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=selected_patrol,
            columns=["serial_number"],
            **(params.get("selected_patrol_serial_as_int") or {}),
        )
        .call()
    )

    patrol_observations = (
        task(get_patrol_observations_from_patrols_df_and_combined_params)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("patrol_observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=selected_patrol_serial_as_int,
            combined_params=patrol_and_events_params,
            **(params.get("patrol_observations") or {}),
        )
        .call()
    )

    convert_patrols_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_patrols_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_observations,
            timezone=get_timezone,
            columns=["patrol_start_time", "patrol_end_time", "fixtime"],
            **(params.get("convert_patrols_tz") or {}),
        )
        .call()
    )

    patrol_events = (
        task(unpack_events_from_patrols_df_and_combined_params)
        .validate()
        .set_task_instance_id("patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=selected_patrol_serial_as_int,
            combined_params=patrol_and_events_params,
            **(params.get("patrol_events") or {}),
        )
        .call()
    )

    convert_events_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_events_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_events,
            timezone=get_timezone,
            columns=["time", "patrol_start_time"],
            **(params.get("convert_events_tz") or {}),
        )
        .call()
    )

    relocs = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=convert_patrols_tz,
            relocs_columns=[
                "patrol_id",
                "patrol_start_time",
                "patrol_end_time",
                "patrol_type__display",
                "patrol_serial_number",
                "patrol_subject",
                "groupby_col",
                "fixtime",
                "junk_status",
                "geometry",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("relocs") or {}),
        )
        .call()
    )

    trajs = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(relocations=relocs, **(params.get("trajs") or {}))
        .call()
    )

    patrol_id_stat = (
        task(extract_first_value_as_string)
        .validate()
        .set_task_instance_id("patrol_id_stat")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=trajs,
            column_name="extra__patrol_serial_number",
            **(params.get("patrol_id_stat") or {}),
        )
        .call()
    )

    patrol_type_stat = (
        task(extract_first_value_as_string)
        .validate()
        .set_task_instance_id("patrol_type_stat")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=trajs,
            column_name="extra__patrol_type__display",
            **(params.get("patrol_type_stat") or {}),
        )
        .call()
    )

    patrol_leader_stat = (
        task(extract_first_value_as_string)
        .validate()
        .set_task_instance_id("patrol_leader_stat")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=trajs,
            column_name="extra__patrol_subject",
            **(params.get("patrol_leader_stat") or {}),
        )
        .call()
    )

    start_time_str = (
        task(extract_formatted_datetime)
        .validate()
        .set_task_instance_id("start_time_str")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=trajs,
            column_name="extra__patrol_start_time",
            aggregator="min",
            time_format="%d/%m/%Y %H:%M",
            **(params.get("start_time_str") or {}),
        )
        .call()
    )

    end_time_str = (
        task(extract_formatted_datetime)
        .validate()
        .set_task_instance_id("end_time_str")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=trajs,
            column_name="extra__patrol_end_time",
            aggregator="max",
            time_format="%d/%m/%Y %H:%M",
            **(params.get("end_time_str") or {}),
        )
        .call()
    )

    total_distance = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_distance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=trajs, column_name="dist_meters", **(params.get("total_distance") or {})
        )
        .call()
    )

    total_distance_km = (
        task(with_unit)
        .validate()
        .set_task_instance_id("total_distance_km")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            original_unit="m",
            new_unit="km",
            value=total_distance,
            **(params.get("total_distance_km") or {}),
        )
        .call()
    )

    total_hours = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_hours")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=trajs,
            column_name="timespan_seconds",
            **(params.get("total_hours") or {}),
        )
        .call()
    )

    total_hours_h = (
        task(with_unit)
        .validate()
        .set_task_instance_id("total_hours_h")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            original_unit="s",
            new_unit="h",
            value=total_hours,
            **(params.get("total_hours_h") or {}),
        )
        .call()
    )

    spatial_features = (
        task(get_spatial_features)
        .validate()
        .set_task_instance_id("spatial_features")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client, **(params.get("spatial_features") or {}))
        .call()
    )

    spatial_features_layer = (
        task(create_spatial_features_layer)
        .validate()
        .set_task_instance_id("spatial_features_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=spatial_features,
            tooltip_columns=[],
            **(params.get("spatial_features_layer") or {}),
        )
        .call()
    )

    local_spatial_file = (
        task(load_local_spatial_file)
        .validate()
        .set_task_instance_id("local_spatial_file")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("local_spatial_file") or {}))
        .call()
    )

    local_spatial_features_layer = (
        task(create_spatial_features_layer)
        .validate()
        .set_task_instance_id("local_spatial_features_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=local_spatial_file,
            tooltip_columns=[],
            **(params.get("local_spatial_features_layer") or {}),
        )
        .call()
    )

    map_overlays = (
        task(collect_optional_layers)
        .validate()
        .set_task_instance_id("map_overlays")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            layers=[spatial_features_layer, local_spatial_features_layer],
            **(params.get("map_overlays") or {}),
        )
        .call()
    )

    patrol_colormap = (
        task(apply_qualitative_color_map)
        .validate()
        .set_task_instance_id("patrol_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=trajs, **(params.get("patrol_colormap") or {}))
        .call()
    )

    selected_traj_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("selected_traj_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_colormap,
            retain_columns=[
                "geometry",
                "column_color",
                "column_label",
                "extra__patrol_serial_number",
            ],
            raise_if_not_found=False,
            drop_columns=None,
            rename_columns=None,
            duplicate_strategy="suffix",
            **(params.get("selected_traj_cols") or {}),
        )
        .call()
    )

    trajs_legend_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("trajs_legend_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("trajs_legend_title") or {}))
        .call()
    )

    trajs_layer = (
        task(create_path_layer)
        .validate()
        .set_task_instance_id("trajs_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=selected_traj_cols,
            legend={
                "title": trajs_legend_title,
                "label_column": "column_label",
                "color_column": "column_color",
            },
            data_url=None,
            **(params.get("trajs_layer") or {}),
        )
        .call()
    )

    events_with_type_display = (
        task(get_event_type_display_names_from_events)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("events_with_type_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            events_gdf=convert_events_tz,
            append_category_names="duplicates",
            **(params.get("events_with_type_display") or {}),
        )
        .call()
    )

    event_details_lookup = (
        task(get_events)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("event_details_lookup")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            event_types=[],
            event_columns=["id", "time", "event_type", "geometry", "event_details"],
            include_details=True,
            include_display_values=False,
            include_null_geometry=True,
            include_updates=False,
            include_related_events=False,
            raise_on_empty=False,
            **(params.get("event_details_lookup") or {}),
        )
        .call()
    )

    event_details_lookup_cols = (
        task(select_columns)
        .validate()
        .set_task_instance_id("event_details_lookup_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=event_details_lookup,
            raise_on_missing=False,
            columns=["id", "event_details"],
            **(params.get("event_details_lookup_cols") or {}),
        )
        .call()
    )

    events_with_display = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("events_with_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=events_with_type_display,
            right=event_details_lookup_cols,
            how="left",
            on="id",
            left_on=None,
            right_on=None,
            left_index=False,
            right_index=False,
            fillna_value=None,
            **(params.get("events_with_display") or {}),
        )
        .call()
    )

    events_details_resolved = (
        task(process_events_details)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("events_details_resolved")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_with_display,
            client=er_client,
            map_to_titles=True,
            ordered=True,
            **(params.get("events_details_resolved") or {}),
        )
        .call()
    )

    events_with_lat_lon = (
        task(add_lat_lon_to_gdf)
        .validate()
        .set_task_instance_id("events_with_lat_lon")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            event_gdf=events_details_resolved,
            **(params.get("events_with_lat_lon") or {}),
        )
        .call()
    )

    event_colormap = (
        task(apply_qualitative_color_map)
        .validate()
        .set_task_instance_id("event_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=events_with_lat_lon, **(params.get("event_colormap") or {}))
        .call()
    )

    event_legend_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("event_legend_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("event_legend_title") or {}))
        .call()
    )

    event_layer = (
        task(create_scatterplot_layer)
        .validate()
        .set_task_instance_id("event_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=event_colormap,
            legend={
                "title": event_legend_title,
                "label_column": "column_label",
                "color_column": "column_color",
            },
            data_url=None,
            **(params.get("event_layer") or {}),
        )
        .call()
    )

    total_events = (
        task(dataframe_count)
        .validate()
        .set_task_instance_id("total_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=event_colormap, **(params.get("total_events") or {}))
        .call()
    )

    total_events_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_events_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Número de eventos",
            decimal_places=0,
            data=total_events,
            **(params.get("total_events_widget") or {}),
        )
        .call()
    )

    total_distance_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_distance_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Distância percorrida (km)",
            decimal_places=2,
            data=total_distance_km,
            **(params.get("total_distance_widget") or {}),
        )
        .call()
    )

    total_hours_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_hours_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Tempo total (h)",
            decimal_places=2,
            data=total_hours_h,
            **(params.get("total_hours_widget") or {}),
        )
        .call()
    )

    map_layers = (
        task(collect_optional_layers)
        .validate()
        .set_task_instance_id("map_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            layers=[map_overlays, trajs_layer, event_layer],
            **(params.get("map_layers") or {}),
        )
        .call()
    )

    patrol_map_view_state = (
        task(view_state_from_layers)
        .validate()
        .set_task_instance_id("patrol_map_view_state")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layers=[trajs_layer, event_layer],
            max_zoom=20,
            **(params.get("patrol_map_view_state") or {}),
        )
        .call()
    )

    patrol_map = (
        task(draw_map)
        .validate()
        .set_task_instance_id("patrol_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=map_layers,
            tile_layers=base_maps,
            static=False,
            title=None,
            view_state=patrol_map_view_state,
            max_zoom=17,
            legend_style={"placement": "bottom-right"},
            output_type="html",
            **(params.get("patrol_map") or {}),
        )
        .call()
    )

    patrol_map_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("patrol_map_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=patrol_map,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="patrol_map.html",
            filename_suffix=None,
            **(params.get("patrol_map_url") or {}),
        )
        .call()
    )

    patrol_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("patrol_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Mapa da patrulha",
            data=patrol_map_url,
            **(params.get("patrol_map_widget") or {}),
        )
        .call()
    )

    patrol_map_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("patrol_map_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html_path=patrol_map_url,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "width": 1280,
                "height": 720,
                "full_page": True,
                "device_scale_factor": 2,
                "wait_for_timeout": 240000,
                "timeout": 0,
                "max_concurrent_pages": 5,
                "serve_local_files": False,
            },
            **(params.get("patrol_map_png") or {}),
        )
        .call()
    )

    events_detail_formatted = (
        task(format_individual_patrol_event_details)
        .validate()
        .set_task_instance_id("events_detail_formatted")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=event_colormap, **(params.get("events_detail_formatted") or {}))
        .call()
    )

    events_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("events_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=events_detail_formatted,
            columns=None,
            table_config=None,
            **(params.get("events_table") or {}),
        )
        .call()
    )

    events_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("events_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=events_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="events_table",
            **(params.get("events_table_html") or {}),
        )
        .call()
    )

    events_table_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("events_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Eventos",
            data=events_table_html,
            **(params.get("events_table_widget") or {}),
        )
        .call()
    )

    download_attachments = (
        task(download_event_attachments)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("download_attachments")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            event_gdf=event_colormap,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            use_index_as_id=False,
            **(params.get("download_attachments") or {}),
        )
        .call()
    )

    report_template_path = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("report_template_path")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("report_template_path") or {}))
        .call()
    )

    norm_template_path = (
        task(remove_file_scheme)
        .validate()
        .set_task_instance_id("norm_template_path")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(path=report_template_path, **(params.get("norm_template_path") or {}))
        .call()
    )

    norm_output_dir = (
        task(remove_file_scheme)
        .validate()
        .set_task_instance_id("norm_output_dir")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("norm_output_dir") or {}),
        )
        .call()
    )

    report_context = (
        task(prepare_individual_patrol_report_context)
        .validate()
        .set_task_instance_id("report_context")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            patrol_id=patrol_id_stat,
            patrol_type=patrol_type_stat,
            patrol_leader=patrol_leader_stat,
            start_time=start_time_str,
            end_time=end_time_str,
            total_distance_km=total_distance_km,
            events=events_detail_formatted,
            **(params.get("report_context") or {}),
        )
        .call()
    )

    individual_patrol_report = (
        task(generate_individual_patrol_report)
        .validate()
        .set_task_instance_id("individual_patrol_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            context=report_context,
            template_path=norm_template_path,
            patrol_map_png=patrol_map_png,
            photo_attachment_paths=download_attachments,
            photo_events=event_colormap,
            output_dir=norm_output_dir,
            **(params.get("individual_patrol_report") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_icmbio_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                total_events_widget,
                total_distance_widget,
                total_hours_widget,
                patrol_map_widget,
                events_table_widget,
            ],
            groupers=groupers,
            time_range=time_range,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
